### ISSUE TITLE
Github action (Travis CI?) for deployment onto gh-pages

### ISSUE THREAD

**Issue by triszt4n** [ftsrg/ftsrg.github.io#139]

**Comment by marci543** [comment]
Relevant part in documentation: https://www.gatsbyjs.com/docs/how-to/previews-deploys-hosting/how-gatsby-works-with-github-pages/#deploying-to-github-pages-from-a-ci-server
Deploy to GitHub Pages from GitHub Actions: https://github.com/ftsrg/cheat-sheets/wiki/GitHub-Actions#deploy-to-github-pages
