### ISSUE TITLE
Add icons from academicons

### ISSUE THREAD

**Issue by micskeiz** [ftsrg/ftsrg.github.io#230]
Academicons (https://jpswalsh.github.io/academicons/) has nice icons for Google Scholar, MTMT, CV et al.

Use these icons on the members page.

**Comment by triszt4n** [comment]
https://www.npmjs.com/package/academicons

**Comment by as3810t** [comment]
Needed: acm, cv, doi, dblp, google-scholar, mtmt, open-access, open-data, orcid, zenodo
